name: Build and Deploy to VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            set -e
          
            WORK_DIR="/var/www/dev.davcreations.in/davcreationsssssss"
          
            cd "$WORK_DIR"
            git config --global --add safe.directory /var/www/dev.davcreations.in/davcreationsssssss
            sudo git pull origin main
          
            # Ensure PM2 is installed
            if ! command -v pm2 &> /dev/null; then
              echo "Installing PM2..."
              npm install -g pm2
            fi
          
            # Build each frontend
            for frontend in customer-frontend admin-frontend superadmin-frontend; do
              echo "Building $frontend..."
          
              cd "$WORK_DIR/$frontend"
              npm install
              npm run build
              npm ci --production
            done
          
            # Restart PM2 applications
            cd "$WORK_DIR"
            pm2 startOrRestart ecosystem.config.js
            pm2 save
